import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./e2e",
  // Single worker — audit is not a CI gate; no parallelism needed.
  workers: 1,
  retries: 0,
  use: {
    baseURL: "http://localhost:5175",
    headless: true,
  },
  projects: [
    // Step 1: generate storageState (login once via committed audit fixtures).
    { name: "setup", testMatch: /auth\.setup\.ts/ },
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        // Reuse the storageState generated by the setup project.
        storageState: "playwright/.auth/user.json",
      },
      dependencies: ["setup"],
    },
  ],
  // Start the Vite dev server in audit mode so it points at the audit backend
  // on port 3013 (loaded from committed .env.audit via --mode audit).
  // reuseExistingServer: true so the server can stay up during the full
  // operator-assisted DeviceControl session (D-03).
  webServer: {
    command: "npm run dev -- --mode audit",
    url: "http://localhost:5175",
    reuseExistingServer: true,
  },
});
